### ISSUE TITLE
User interface suggestions

### ISSUE THREAD

**Issue by ralfhauser** [water-fountains/proximap#58]
E.g. upper Hegibachstr.

![image](https://user-images.githubusercontent.com/1681677/43423890-dfcc795e-944d-11e8-8bf4-96e75613f7fd.png)

1) vs. 2) is it Verteilnetz or unknown ?
Three 3) Add Link to a contribution template
Four 4) if empty, probably don't show ?

**Comment by ralfhauser** [comment]
If the not-yet-approval of https://www.wikidata.org/wiki/Wikidata:Property_proposal/type_of_water is the reason for 1vs2, please spend some time (maybe together with Cristina) to re-animate it.
If this still doesn't work within a few weeks, we'll have to base that aspect as a fall-back on the original WVZ dataset.

**Comment by mmmatthew** [comment]
data is now consistent. type of water is currently stored in OSM, but it should be stored in wikidata. See proposal https://www.wikidata.org/wiki/Wikidata:Property_proposal/type_of_water.

Points 3 and 4 are documented in the pipeline

**Comment by ralfhauser** [comment]
"type of water" available since aug 14, 2018, please do one more manual import to facilitate 1) and 2)

**Comment by mmmatthew** [comment]
A manual import has been completed. 

Regarding 3, a design concept is being developed for phase S2
Regarding 4, this has been fixed.
