### ISSUE TITLE
documentation: community contribution guides

### ISSUE THREAD

**Issue by mmmatthew** [water-fountains/proximap#68]
Documentation for how to update a fountain's information, images, coordinates, etc.

**Comment by mmmatthew** [comment]
not useful issue

**Comment by ralfhauser** [comment]
What did you do ?
Where can I find them ?

**Comment by mmmatthew** [comment]
See following commits:
71ff3f83eb07d05763b8fdfa56ce2f50f84d86bc - Main pull request that introduces the feature
d461b0cb82fa68630100a62e0d6c6f0b87ae9cc9 - Bug fix
00a7f2d5bc6b2f488b14ca28cc1f9796f6b414b8 - Improvement
