### ISSUE TITLE
Fountain filters

### ISSUE THREAD

**Issue by mmmatthew** [water-fountains/proximap#71]
- [x] replace year slider with manual entry

**Comment by mmmatthew** [comment]
Many relevant commits here: https://github.com/water-fountains/proximap/search?utf8=%E2%9C%93&q=filter&type=Commits

Latest: include English, German, and French fountain names in search (393dd45b4e51a51b666195614f3c93c96e4fc8dd)

**Comment by mmmatthew** [comment]
> * [x]  replace year slider with manual entry

Fix: 7c3617c7c3a767c6fa7c18030f15143ad1898e4b

**Comment by ralfhauser** [comment]
1) What was the reason to replace the slider with manual entry ?

**Comment by ralfhauser** [comment]
2) how difficult would it be to have both - slider and direct date entry ?
