### ISSUE TITLE
step-by-step navigation

### ISSUE THREAD

**Issue by mmmatthew** [water-fountains/proximap#72]
- [ ] improve design

**Comment by ralfhauser** [comment]
what did you do?
which files contain the changes ?

**Comment by mmmatthew** [comment]
The following commits are relevant:
- 105e2c6fb5657ec3e6f993e0a78cc8a899721b80
- 2aca7abd5333c22f82cd0c1299b37db1869cb5bd
- a2a6fc7915516b173e33233293115d0a11a7bee5
- de9e8fef493874cc357517dce91d20328f24bd17
- 6bc9230f1f505770c20c54192df127d6382134d5

Important: if user location is undefined, then show an alert
9b0914a2f568ef6119afa19ff3014bfdb04a4384
